### ISSUE TITLE
Fuzzy matching does not cover all types

### ISSUE THREAD

**Issue by jakobbraun** [exasol/hamcrest-resultset-matcher#20]
The current fuzzy matching implementation did not cover some edge case conversions.

## Acceptance Criteria:

Add a fuzzy matching mode that matches if the values are equal, independent of the type.

**Comment by jakobbraun** [comment]
closed since not intended

**Comment by redcatbear** [comment]
@jakobbraun, please improve issue title. This title is a ticket anti-pattern. :-)

**Comment by jakobbraun** [comment]
Closed by #23
